import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/sidebar'
import CreateOrderButton from '../components/createOrderButton'
import PayOrderButton from '../components/payOrderButton'
import ClearOrderButton from '../components/clearOrderButton'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';
import TableDisplay from '../components/table';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      {/* <TableDisplay /> */}
      <main className={styles.main}>

        <div>
          <CreateOrderButton />
          <PayOrderButton />
          <ClearOrderButton />
        </div>

      </main>
    </div>
  )
}

export default Home
